artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/devarajv88/walmart-sales-dataset
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/walmart.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/walmart.csv


model_trainer:
  root_dir: artifacts/model_trainer
  transformed_data_path: artifacts/data_transformation/transformed_scaled_data.csv
  clustered_data_path: artifacts/model_trainer/clustered_data.csv
  test_data_path: artifacts/model_trainer/test_data.csv
  model_save_path: artifacts/model_trainer/model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer/model.joblib
  test_data_path: artifacts/model_trainer/test_data.csv
  evaluation_metrics_path: artifacts/model_evaluation/metrics.json
  mlflow_uri: https://dagshub.com/JoshuaVictorL/Customer-Segmentation-Project.mlflow
  target_column: Cluster